name: red_thread
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+8
  google_mlkit_face_detection: ^0.9.0
  image_picker: ^1.0.6
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  google_mlkit_commons: ^0.6.1
  path: ^1.8.3
  path_provider: ^2.1.2
  go_router: ^13.0.1
  sign_in_button: ^3.2.0
  url_launcher: ^6.2.4
  intl: ^0.19.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_animate: ^4.5.0
  introduction_screen: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
