name: red_thread
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+8
  google_mlkit_face_detection: ^0.9.0
  image_picker: ^1.0.6
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  google_mlkit_commons: ^0.6.1
  path: ^1.8.3
  path_provider: ^2.1.2
  go_router: ^13.0.1
  url_launcher: ^6.2.4
  intl: any
  flutter_keyboard_visibility: ^6.0.0
  flutter_animate: ^4.5.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  firebase_messaging: ^14.9.2
  dropdown_search: ^5.0.6
  flutter_native_splash: ^2.4.0
  flutter_localizations:
    sdk: flutter
  flutter_contacts: ^1.1.8
  geolocator: ^12.0.0
  firebase_database: ^10.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
  use_deferred_loading: true
  arb_dir: lib/l10n
  template_arbs:
    - lib/l10n/app_en.arb
    - lib/l10n/app_ja.arb
  output_dir: lib/generated