name: red_thread
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  amplify_auth_cognito: ^1.6.1
  amplify_authenticator: ^1.5.2
  amplify_flutter: ^1.6.1
  amplify_api: ^1.0.0
  flutter:
    sdk: flutter
  jitsi_meet_flutter_sdk: ^0.1.9
  camera: ^0.10.5+8
  google_mlkit_face_detection: ^0.9.0
  image_picker: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
